language: cpp

sudo: true

os:
  - linux
#  - osx

dist: xenial

services:
  - docker

compiler: gcc

env:
  - UNATTENDED=--assume-yes

addons:
  apt:
    # build tools
    - git
    - pkg-config
    - ruby
    - autoconf
    - libtool
    - cmake
    - make
    - gcc
    - g++
    - gettext
    - openjdk-8-jre-headless
    - tree
    # dev libraries
    - libcairo-dev
    - libspiro-dev
    - libpng-dev
    - libjpeg-dev
    - poppler-data
    - libpango1.0-dev
    - liblcms2-dev
    - libxml2-dev
    - libuninameslist-dev
#  homebrew:
#    packages:
#      - autoconf
#      - pkg-config
#      - git
#      - cmake
#      - freetype
#      # Poppler-specific packages
#      - fontconfig
#      - jpeg
#      - nss
#      # libuninameslist-specific packages
#      - automake
#      - libtool
#      # fontforge-specific packages
#      - python
#      - glib
#      - xml2
#      - libspiro
#      - gettext
#      # pdf2htmlEX-specific packages
#      - cairo
#      - pango
#  sauce_connect: true

matrix:
  fast_finish: true
#  allow_failures:
#    - os: osx # Until the build passes, then re-enable.

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./buildScripts/getPoppler
  - ./buildScripts/buildPoppler
  - ./buildScripts/installPoppler
  - ./buildScripts/getFontforge
  - ./buildScripts/buildFontforge
  - ./buildScripts/installFontforge
  - ./buildScripts/buildPdf2htmlEX
  - ./buildScripts/installPdf2htmlEX
  - ./buildScripts/createAppImage
  - ./buildScripts/createDockerImage 
  - docker push $DOCKER_USERNAME/pdf2htmlex
