language: cpp

sudo: true

os:
  - linux
#  - osx

dist: bionic

services:
  - docker

compiler: gcc

env:
  global:
    - UNATTENDED="--assume-yes"

#addons:
#  apt:
#  update: true
#  packages:
#    # build tools
#    - git
#    - pkg-config
#    - ruby
#    - autoconf
#    - libtool
#    - cmake
#    - make
#    - gcc
#    - g++
#    - gettext
#    - openjdk-8-jre-headless
#    - tree
#    # dev libraries
#    - libcairo-dev
#    - libspiro-dev
#    - libpng-dev
#    - libjpeg-dev
#    - poppler-data
#    - libpango1.0-dev
#    - liblcms2-dev
#    - libxml2-dev
#    - libuninameslist-dev
#  homebrew:
#    packages:
#      - autoconf
#      - pkg-config
#      - git
#      - cmake
#      - freetype
#      # Poppler-specific packages
#      - fontconfig
#      - jpeg
#      - nss
#      # libuninameslist-specific packages
#      - automake
#      - libtool
#      # fontforge-specific packages
#      - python
#      - glib
#      - xml2
#      - libspiro
#      - gettext
#      # pdf2htmlEX-specific packages
#      - cairo
#      - pango
#  sauce_connect: true

matrix:
  fast_finish: true
#  allow_failures:
#    - os: osx # Until the build passes, then re-enable.

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./buildScripts/getBuildTools     || travis_terminate 1;
  - ./buildScripts/getDevLibraries   || travis_terminate 1;
  - ./buildScripts/getPoppler        || travis_terminate 1;
  - ./buildScripts/buildPoppler      || travis_terminate 1;
  - ./buildScripts/installPoppler    || travis_terminate 1;
  - ./buildScripts/getFontforge      || travis_terminate 1;
  - ./buildScripts/buildFontforge    || travis_terminate 1;
  - ./buildScripts/installFontforge  || travis_terminate 1;
  - ./buildScripts/buildPdf2htmlEX   || travis_terminate 1;
  - ./buildScripts/installPdf2htmlEX || travis_terminate 1;
  - ./buildScripts/createAppImage    || travis_terminate 1;
  - ./buildScripts/createDockerImage || travis_terminate 1;
  - docker push $DOCKER_USERNAME/pdf2htmlex
