language: cpp

sudo: true

os:
  - linux
#  - osx

dist: bionic

env:
  global:
    - POPPLER_SOURCE="https://gitlab.freedesktop.org/poppler/poppler.git"
  matrix:
    - POPPLER_RELEASE="poppler-0.81.0"

compiler: gcc

addons:
  apt:
    update: true
    packages:
      - build-essential
      - autoconf
      - git
      - pkg-config
      - cmake
      - make
      - gcc
      - g++
      # - ca-certificates
      # - libfreetype6-dev
      # Poppler-specific packages
      - libfontforge-dev
      - libfontconfig-dev
      - libjpeg-dev
      - libpng-dev
      - libnss3-dev
      # pdf2htmlEX-specific packages
      - default-jre
      - libcairo-dev
      - libspiro-dev
      - libpango1.0-dev
      - poppler-data
#  homebrew:
#    packages:
#      - autoconf
#      - pkg-config
#      - git
#      - cmake
#      - freetype
#      # Poppler-specific packages
#      - fontconfig
#      - jpeg
#      - nss
#      # libuninameslist-specific packages
#      - automake
#      - libtool
#      # fontforge-specific packages
#      - python
#      - glib
#      - xml2
#      - libspiro
#      - gettext
#      # pdf2htmlEX-specific packages
#      - cairo
#      - pango
#  sauce_connect: true

matrix:
  fast_finish: true
#  allow_failures:
#    - os: osx # Until the build passes, then re-enable.

before_install:
  - pwd
  - ls -la
  - ./.travisScripts/buildPoppler.sh
  - pwd
  - ls -la
  - ./.travisScripts/installPoppler.sh
  #- ./.travisScripts/setupTests.sh

script:
  - ./dobuild
  - ./doinstall
  - /usr/bin/pdf2htmlEX -v
