language: cpp

sudo: true

os:
  - linux
#  - osx

dist: xenial

services:
  - docker

compiler: gcc

#addons:
#  homebrew:
#    packages:
#      - autoconf
#      - pkg-config
#      - git
#      - cmake
#      - freetype
#      # Poppler-specific packages
#      - fontconfig
#      - jpeg
#      - nss
#      # libuninameslist-specific packages
#      - automake
#      - libtool
#      # fontforge-specific packages
#      - python
#      - glib
#      - xml2
#      - libspiro
#      - gettext
#      # pdf2htmlEX-specific packages
#      - cairo
#      - pango
#  sauce_connect: true

matrix:
  fast_finish: true
#  allow_failures:
#    - os: osx # Until the build passes, then re-enable.

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./buildScripts/doItAll
  - docker push $DOCKER_USERNAME/pdf2htmlex
